### ISSUE TITLE
Page mismatch

### ISSUE THREAD

**Issue by marcverhagen** [lappsgrid-incubator/askme-web-next#2]
This error is sometimes written to the standard output:

```
NormalizeError: Requested and resolved page mismatch: /../../mnt/mtd/Config/Account2 /mnt/mtd/Config/Account2
    at Object.normalizePagePath (/home/ubuntu/askme/git/askme-web-next/node_modules/next/dist/shared/lib/page-path/normalize-page-path.js:15:19)
    at Object.getMaybePagePath (/home/ubuntu/askme/git/askme-web-next/node_modules/next/dist/server/require.js:43:86)
    at NextNodeServer.hasPage (/home/ubuntu/askme/git/askme-web-next/node_modules/next/dist/server/next-server.js:164:32)
    at Router.checkPage (/home/ubuntu/askme/git/askme-web-next/node_modules/next/dist/server/router.js:49:35)
    at Object.fn (/home/ubuntu/askme/git/askme-web-next/node_modules/next/dist/server/router.js:109:40)
    at Router.execute (/home/ubuntu/askme/git/askme-web-next/node_modules/next/dist/server/router.js:253:48)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async NextNodeServer.run (/home/ubuntu/askme/git/askme-web-next/node_modules/next/dist/server/base-server.js:384:29)
    at async NextNodeServer.handleRequest (/home/ubuntu/askme/git/askme-web-next/node_modules/next/dist/server/base-server.js:322:20)
PageNotFoundError: Cannot find module for page: /../../mnt/mtd/Config/Account2
    at Object.getMaybePagePath (/home/ubuntu/askme/git/askme-web-next/node_modules/next/dist/server/require.js:46:15)
    at NextNodeServer.hasPage (/home/ubuntu/askme/git/askme-web-next/node_modules/next/dist/server/next-server.js:164:32)
    at Router.checkPage (/home/ubuntu/askme/git/askme-web-next/node_modules/next/dist/server/router.js:49:35)
    at Object.fn (/home/ubuntu/askme/git/askme-web-next/node_modules/next/dist/server/router.js:109:40)
    at Router.execute (/home/ubuntu/askme/git/askme-web-next/node_modules/next/dist/server/router.js:253:48)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async NextNodeServer.run (/home/ubuntu/askme/git/askme-web-next/node_modules/next/dist/server/base-server.js:384:29)
    at async NextNodeServer.handleRequest (/home/ubuntu/askme/git/askme-web-next/node_modules/next/dist/server/base-server.js:322:20) {
  code: 'ENOENT'
}
```

**Comment by marcverhagen** [comment]
Closed because it does not seem to happen anymore.
